import "./globals.css";
import '@mantine/core/styles.css';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { Header } from "@/components/header";

export const experimental_ppr = true

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-15 md:px-35`}
      >
        <MantineProvider>
          <Header />
          {children}
          {modal}
          <div id="user-login-modal" />
          <div id="user-logout-modal" />
        </MantineProvider>
      </body>
    </html>
  );
}
